routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

// Route::resource('Store', "StoreController");
// Route::view('Store','StoreController');

Route::resource('Categories', "CategoriesController");
Route::resource('Posts', "PostsController");

Route::resource('Users', "UsersController");
Route::get('users-form','UsersController@form')->name('Users.form');

// Route::get('users-form','UsersController@destory')->name('Users.form');
// Route::delete('/Users/{id}', UsersController@destroy);
// Route::get('users-edit','UsersController@edit')->name('Users.edit');
// Route::post('users-store','UsersController@store')->name('Users.store');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Users.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Users extends Model
{
    //
}

app/Http/Controllers/Users.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;


class Users extends Controller
{
    //
    function list( ){

        return Users::all();
    }
}
?>

app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;
use Illuminate\Http\Request;
use App\Users;
use Validator;
use App\Http\Requests\StoreFormValidation;


class UsersController extends Controller
{
    public function index()
    {

        $users = Users::all();
        return view('users.index')->with(compact(['users']));
    }

    public function form()
    {
        return view('users.form');
    }

    public function edit(Users $User)
    {
        //  return($User);
        $ids = Users::find($User->id);
       if(empty($ids)){
            return abort(404);
       }
       return view ('users.edit')->with('Users', $ids);
    }

    public function destroy(){

    }

    public function store(StoreFormValidation $request) {


        $users = new users;
        $users->users = $request->users;
        $users->contact = $request->contact;
        $users->save();

        return redirect()->route('Users.index');


    }

    Public function update(Request $request, Users $User){

         //return($request);
            $users = Users::find($User->id);
            $users->users = $request->users;
            $users->contact = $request->contact;
            //return ($users);
            $users->save();

            // $users = Users::all();
            // // return $posts;
            // return view('users.index')->with(compact(['users']));
        return redirect()->route('Users.index');


    }

    public function show(Users $User){

        //return($User);
        $users = Users::find($User->id);
        $users->delete();

        // $users = Users::all();
        //     // return $posts;
        //     return view('users.index')->with(compact(['users']));

        return redirect()->route('Users.index');


    }

}

resources/views/users/edit.blade.php
    <form action="{{route('Users.update',['users' => $Users->id])}}" method="post">
    @method('PUT')
    @csrf
    <input type="text" name="users" value="{{$Users->users}}" >
    <input type="text" name="contact" value="{{$Users->contact}}" >
    <button type="submit"> UPDATE</button>
    </form>

resources/views/users/form.blade.php
<h1>
    Users
</h1>

    <form action="{{route('Users.store')}}" method="post">
        @if(count($errors)>0)
            @foreach ($errors->all() as $error)
            <p>
                {{$error}}
            </p>


            @endforeach
        @endif
    @csrf
        <Label>Name :</Label><input type="text" name="users"><br><br>
        <label>Contact :</label><input type="text" name="contact"><br><br>
        <button type="submit"> SAVE</button>
    </form>

resources/views/users/index.blade.php
<div>
    <button><a href="{{ route('Users.form')}}">Add Users</a></button>
<div>

@if(count($users))
<table>
    <tr><td>Name</td><td>Contact</td><td colspan="2">Action</td></tr>
    @foreach($users as $user)
    <tr><td><input readonly type="" name="users" value="{{$user->users}}" ></td>
        <td><input readonly type="" name="contact" value="{{$user->contact}}" ></td>
    <td><button><a href="{{ route('Users.edit',['user' => $user->id]) }}">Edit</a></button></td>
    <td><button><a href="{{ route('Users.destroy',['user' => $user->id]) }}">DELETE</a></button></td>
    @endforeach
</table>
@else
 <p> No Post Found<p>
 @endif